
name: Update Tides Overlay

on:
  schedule:
    - cron: "*/15 * * * *"  # Cada 15 minutos
  workflow_dispatch:       # Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar librerías necesarias
      run: |
        pip install requests

    - name: Ejecutar script de mareas
      run: python import_tides_overlay.py

    - name: Hacer commit si hay cambios
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add overlay_tides.json
        git diff --cached --quiet || git commit -m "🔄 Actualización de overlay_tides.json"
        git push
